RegisterServerEvent('mrp-login:disconnectPlayer')
AddEventHandler('mrp-login:disconnectPlayer', function()
    local src = source
    DropPlayer(src, "You have been disconnected from the server")
end)

RegisterServerEvent("mrp-login:licenses")
AddEventHandler("mrp-login:licenses", function()
    local src = source
    local user = exports["mrp-core"]:getModule("Player"):GetUser(src)
    local char = user:getVar("character")
    exports.ghmattimysql:execute("INSERT INTO user_licenses (type, owner) VALUES (@type, @owner)", {['@type'] = "Firearm",['@owner'] = char.id})
    exports.ghmattimysql:execute("INSERT INTO user_licenses (type, owner, status) VALUES (@type, @owner, @status)", {['@type'] = "Driver", ['@owner'] = char.id, ['@status'] = "1"})
    exports.ghmattimysql:execute("INSERT INTO user_licenses (type, owner) VALUES (@type, @owner)", {['@type'] = "Hunting",['@owner'] = char.id})
    TriggerClientEvent("player:receiveItem", src, "backpack", 1)
end)

RegisterServerEvent("backpack:give:items")
AddEventHandler("backpack:give:items", function()
    local src = source
    TriggerClientEvent("player:receiveItem", src, "mobilephone", 1)
    TriggerClientEvent("player:receiveItem", src, "radio", 1)
    TriggerClientEvent("player:receiveItem", src, "idcard", 1)
    TriggerClientEvent("player:receiveItem", src, "water", 4)
    TriggerClientEvent("player:receiveItem", src, "sandwich", 4)
    TriggerClientEvent("player:receiveItem", src, "lockpick", 2)
    TriggerClientEvent("player:receiveItem", src, "firstaid", 3)
    TriggerClientEvent("player:receiveItem", src, "joint", 10)
    TriggerClientEvent("player:receiveItem", src, "headphones", 1)
    TriggerClientEvent("player:receiveItem", src, "fishingrod", 1)
    TriggerClientEvent("player:receiveItem", src, "crabcage", 1)
end)
